### ISSUE TITLE
Sampling distribution curve

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#10]
SE lines—height now seems fine.  SE lines are centred around mu, and based on curve SE, which is correct.

Sampling distribution curve should be based on population mu and sigma, and N, not sample values, so should not bounce around as more samples are taken.

When the first dropping means arrive at the bottom, sometimes taking one more sample shows a curve that’s too high and too wide, then taking another gives a much smaller curve, about right for just two means. Doesn’t always seem to work like that. More often, I think, when using ‘Run’ that is not too slow, rather than repeated ‘Take sample’, so maybe it’s a timing issue. Or use fast ‘Run’ to nearly fill screen, then take a couple more single samples. It might be that the first curve is calculated for all the means on the screen, then a sample or two later the curve is just for the small number of means in the heap? Or use ‘Run’ and watch carefully, and see a momentary flash of a higher curve as the first mean hits the bottom, before a smaller curve appears and then grows.

There are some funny checkbox dependencies. With all Panel 5 boxes ‘on’, Run to see a heap, then Stop. Click the boxes off and on. Top box is ok—heap toggles ok. Next two boxes—click either off does work. Now click either on again and display doesn’t update until we take one or two extra samples.

**Comment by gfmoore** [comment]
Added: update Curve SE value.

**Comment by gfmoore** [comment]
I think this is sorted now. I added some checks such that the curve cannot be displayed unless the heap is also displayed. If the heap is checked off, so is the curve. On checking heap again and then checking curve no curve displayed as no heap to display against.

I'm assuming the CurveSE value is the sigma/root(n) as for the curve.

Can we close this now? :)

**Comment by gdcumming** [comment]
Curve looks great and seems to behave well.

Except that the curve always (often?) seems to be too high. I.e. the vertical scaling factor seems a bit high. Run sampling for a while, stop, then mentally shift the piled means that poke about the curve to an adjacent column that stops short of the curve. Typically (always?) have space under the curve. I.e. space under exceeds area of dots that are piled above curve.

Might you be calculating the desired area under the curve using total means taken instead of means currently in heap? Not sure that's quite right, but worth checking.

**Comment by gfmoore** [comment]
The curve is calculated using mu and the se (sigma/sqrt(samplesize)) as requested?

I then scale it to the pixels available.

If you want it less high I can adjust the scale.

The production of the heap seems to have a bias to the right . I have to look into this further as I mentioned in another issue (where we have red blobs) as occasionally when mu is known they don't always fall right. 

In order to cater for responsive web pages (i.e. the pixels available for a browser width can change depending on the user and the pixel resolution of the device) I have to approximate where the bars are! It's not easy. You have to recall that I am dealing with two views - the pixel view and the mathematical view and also the discretised view. It's getting too hard for me to be honest. This is the most complex program I've ever written and I'm starting to lose the plot!

**Comment by gdcumming** [comment]
0.3.30

Oh no--above all we are not trying to make your life hell! Really!

Bob and I agree that we need to satisfice. (A famous word used by Herb Simon, cognitive psychologist (among other things) who won the Nobel in economics for his research on decision making, and helped found AI.) Get things as good as they need to be, and move on!

Yep, curve on the heap should always be normal, mean mu and SD=the se you specify above.

The only issue is the vertical scaling factor. I calculated that in ESCI on the fly (as you do), so that the area under the curve was equal (or as close as possible) to the sum of the areas of the little squares (or rectangles) occupied by the means in the heap. (NB the means currently in the heao,) If that is hard, or impossible, to calculate, then maybe leave things as they are and apply a vertical scale factor so the fit looks good, at least mostly. 

To my eye a vertical scale factor of around .9 looks as tho' it might be OK. If that's simple to build in, give it a try?

I hadn't noticed any bias to the right in the heap. Do you mean that more points seem to lie on or beyond the curve on the RHS than on the LHS, looking esp. at the tails? Are you referring to the red means in the heap and how they fall in relation to the +/-MoE lines? I've looked, and can't see a consistent bias. (As we've discussed, with sigma known, we expect to see a few red means apparently on the 'wrong' side of the +/_ MoE lines because of adjustments so that means sit neatly into columns.) I'm not sure this is worth further pain, unless easy to diagnose and adjust. We are always going to have some small display distortions because of pixelation, and/or bin width granularity.

**Comment by gfmoore** [comment]
I love that word - satisfice - the 90-10 (or 80-20) rule. When I did business analysis that's what I'd say to the executives. Get 90% of what you need easily accomplished. The other 10%, which often happens rarely anyway) get someone with a brain to sort out! Taught that by an ex-IBM salesman, though I bet he didn't let on to IBM that he did that! :()

Anyway I've scaled it down by .9 - again this one is easy to fudge. I can easily count the means in the heap, but because that will depend on the pixels being utilised then, well I can't get my head around the calcs. It's probably easy,  but can we leave it for now and re-visit if it becomes an issue?

As to the bias thing. What I'm noticing is is that on either side of the mu line I'm getting means wanting to go to the right more than the left. (That's how it seems to me anyway). I need to revisit this code anyway to see if I can get the red means to fall properly.

**Comment by gdcumming** [comment]
The .9 really helps. To my eye, still a tiny bit high on average. Could you easily make the factor .88? (Of course, just being picky.)

I still don't understand your last comment. I don't on average see more of the heap to the right of mu than to the left. Is that what you mean, or something different? I guess it never hurts to check code...

**Comment by gfmoore** [comment]
Any better? Looks a little low to me?

Where would you like the top of the curve to be? Should it match the top of the heap?

**Comment by gdcumming** [comment]
I've tried different screens, different sigma values, different N, all with normal populations. Sometimes the curve looks a bit high early in a run, about right later. A bit different for narrow and wide heaps: maybe the curve is a bit low for narrow, but a bit high for wide.

Overall I'd say that the current scale factor is good. Let's stick with it for the moment.

Rather than curve max height, I'm focussing on number of means above or outside the curve vs amount of space inside the curve. In other words, columns of means that end below curve vs those that extend above it.

In the course of trying some narrow heaps (eg sigma = 7, N = 100) I saw for the first time what I'm guessing you refer to when you say the means seem to fall a little to the right. A little more of the heap falls to the right of the mu line than to the left, and does so pretty consistently. I tried varying mu and sigma values by small amounts, in case it's a matter of where bin (column) boundaries happen to fall in relation to pixels. But still the same small asymmetry.

I don't think it's a big problem, but maybe worth, as you say, checking coding, with a particular eye to bin boundaries in relation to mu. Would it make sense to choose those boundaries so mu is always on a bin boundary, or in the middle of a bin? Probably that's tricky and not worth doing. I'm not going to lose any sleep about this possible slight mean heap bias to the right.
