### ISSUE TITLE
Outrageous suggestion, colour in mean heap

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#12]
In the mean heap, use colour of means to show capture or not, 

Display means in mean heap as (deeper) green or red, accordingly as their CI captures or misses mu. With mu assumed known, red means would all sit neatly in the tails beyond the ±MoE lines. With that assumption turned off, the red means would be mainly in or near those tails, but mixed with some green means. That of course would mean recording the capture or not status for each mean, for both sigma known and sigma unknown cases. Which your buffer does? (If doing that leads to a limit, e.g. 600 or some bigger number, on the number of most recent means displayed, then that’s ok). I did something close to that in the ‘dance of the correlations’ in ESCI for the first book, from the website: See the Sample r sheet in ESCI chapters 14-15, for UTNS. (Sent as an attachment to email on 8 June.)

**Comment by gfmoore** [comment]
Well it's not an outrageous suggestion at all. However it has proved quite a problem. Programming would be so easy if it weren't for edge cases - that's what takes up my life :)

So you will notice some anomalies when the  population sigma is known.

Technically a miss should lie outside the +/1 MoE yes?
However in creating the histogram for the mean heap I create discrete buckets. The number of these varies according to the screen width, so that it all fills. When a mean drops it goes into one bucket or the other - depending on the rounded values. (Now I have tried all sorts of tweaks using forcing to upper value when > mean, and forcing to a lower value when on the other side, (Math.ceil and Math.floor) but it's so tricky. 

if you watch a mean drop carefully you will see that it picks one bar or the other to become part of.

The upshot is that sometimes a red falls inside the +/- MoE bars and sometimes outside when on that little width between the two. If I try and force the issue then I still get some greens outside the bars.

I'll have another look tomorrow, but I'm losing the plot at the moment. You might have a clearer mind on it :) Well you are the Prof! lol.

For sigma unknown it's not so much as an issue because as you said, there will be some inside anyway.

Well it's a start.

**Comment by gdcumming** [comment]
I've been there. I understand exactly the challenges!

I'm happy it you make columns ('buckets') of a convenient width to give the lovely just-touching stacking of means in the mean heap. Each +/- MoE vertical will typically land within the width of some column. It's fine to have that column of means a mixed pile of red and green. In the long run, with sigma known, the proportion of green will correspond to the proportion of the column width that lies inside the +/-MoE verticals.

The important thing is that you keep the accurate value of every mean and CI so that capture is calculated correctly, so we can take long runs and see C% capture, very closely. I have yet to take up your suggestion to do some overnight runs. I will. That will take Lindy back to the days when I'd often run simulations overnight, then get up early to record results and maybe start another shorter run.

Hoping all is well with this, I'll close.

**Comment by gfmoore** [comment]
I haven't given up on the red green interface :)
