### ISSUE TITLE
Outrageous suggestion, draw-a-curve

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#14]
Draw-a-curve? 

ESCI can display normal, rectangular, or skew-normal pop distribution curves, then sample from these. The main use of these was to demonstrate the central limit theorem (CLT). It's compelling to see the sampling distribution of the mean turn out to be so close to normal, even when the pop is strongly skewed, even with samples as small as N=6. The normal distribution appears out of thin air, so must represent some fundamental property of how the universe works. 

In StatPlay, software that Neil Thomason and I developed 20+ years ago (in Visual C++; we had to raise grants and hire programmers) there was the forerunner of CIjumping. One option was to draw-a-curve for the pop pdf. Use the mouse, sweep it left to right in the upper (pop) panel to make whatever crazy curve you liked. Any number of peaks and troughs, any crazy shape. Then sample from this. Perhaps it was even more compelling that the sampling distribution of the mean is approx normal, even for quite small N, even for wildly crazy pop curves.

**Comment by gfmoore** [comment]
Well, since I decided to work on implementing the skew, I went ahead and did this as well.
Have to say I'm quite pleased. I'm sure that it could draw better and certainly fill better, but its a good start.

Note I have yet to figure out how to get a random variable from this. I'm sure I'm going to have to do a sort of numerical integration approximation type thing. Not really thought it through yet.

If you are into thinking, the pdf is stored as an array of what are called in JavaScript objects of the form {x: xval, y: yval}  . There could be any number of values depending on how many points are in the drawn object - made up of little line segments at the moment.

(I can see little rectangles!)

Oh and note you can't go back on yourself when drawing, because that would be silly, though there is an end effect that I haven't looked into yet. 

I don't know whether to draw ordinates at the start and end of the curve?

**Comment by gdcumming** [comment]
So nice to see a start on this!

I actually did a version of this in Excel. It worked, but was so tricky and flaky that I was sure it wouldn't survive future revisions of Excel, which too often drop critical features (which maybe were undocumented). So I didn't include it in any ESCI release.

My memory from way back is that you could start the L-to-R sweep of the mouse from anywhere on the left side of the display rectangle or any point on the bottom. Then move L to R. If you backtracked, then, as with yours, the trace just waited until you came back sufficiently far to the R to continue, with perhaps a vertical step being inserted to give one curve. Finish by dropping below the bottom or crossing over the R side of the rectangle. Yes a vertical was inserted at start and/or finish if necessary, to give a closed area under the curve. Maybe a horizontal line segment along the bottom axis also filled in automatically, if needed.

Another possibility would be to display a small circle at bottom left and bottom right of the pop display rectangle, as soon as 'Custom' was selected. User starts by clicking in left circle and finishes by releasing mouse in right hand circle.

Then the curve would normalise itself, so the max height was just below top of rectangle.

I believe we stored it simply as a series of perhaps 300-500 (I'm guessing) ordinates. Consider these as little piles of squares. Sample a data value by choosing a random square under the curve.

Need to calculate and display mean and SD, which perhaps could appear as values in the mu and sigma boxes next to the sliders--if that's possible without messing up the dropdowns used for other pop shapes.

**Comment by gfmoore** [comment]
Can we close this yet?

**Comment by gdcumming** [comment]
Sorry, I haven't played with one for a while. 

When it all works, this is truly great. The red drawn curve turns blue, can be filled, and I can take samples. All terrific.

But if I try to draw a new pop, various things can happen. The first curve doesn't automatically disappear if I try to draw a new one. This new curve I draw might stay red and not be able to be filled, and mu and sigma still show 'NaN' (better I think if that was a dash or three dots, if possible).  If I switch to a different shape population, then switch back, I might still see the red drawn curve, of sometimes just part of it. 

We might need a 'clear curve' checkbox just for custom? Perhaps the problem is that it's not obvious where I can or should start drawing and where stop. If I start just below the horiz axis I don't get a curve, at least not one that turns blue. If I click first somewhere in the uppper display area, towards the left end, sometimes I get a curve that turns blue, sometimes just a red curve that stays red, whatever I try. I can't find any really regular pattern of behaviour here that might help diagnosis.

Do we allow any of those possibilities for starting (and similarly for stopping) drawing a curve? Or specify just one that can be implemented readily? Or, if necessary, display a small circle at start and finish that indicate where the drawing must start and finish?

I hope this is not too hard because, as I say, when it works (turns blue) it's great.

**Comment by gfmoore** [comment]
That's odd.
First try keeping the fill turned off, it really slows things down.

Check the  Population, check the custom, use mouse to draw curve. Red then on mouse up Blue. Now mousedown and draw a new curve, mouse up blue. 
You can right click to clear.

Now check fill and wait, maybe a long time on ipad!!!
Turn off fill

If you change between normal, rectangular and skew and back to custom it should remember the curve you drew.

**Comment by gfmoore** [comment]
The fill is too slow, I'll have another look at it. (I'll open another issue.)

**Comment by gfmoore** [comment]
Oh there is a bug when fill checked, it's not clearing the fill when drawing a new custom curve - I'll fix it.

**Comment by gfmoore** [comment]
Fixed the bug (I hope and not introduced any new ones) and replaced NaN with - and moved sliders to the left.

**Comment by gdcumming** [comment]
Ah, right click to clear. Makes sense but I hadn't tried that.  I guess the popout could explain.

Works much better. Yes, fill is slow.

One remaining issue: Start drawing, then mouseup in the display area or after leaving the right hand edge of the display area: all works well. But if exit the display area over the lower or upper boundaries, then mouseup, the curve stays red. Indeed, come back into the display area (a little to the right of the exit point) and move mouse: the red curve continues, mouse still up. Go back left, mousedown, and draw a second red curve. Can do this multiple times if every time exit the top or bottom of the display area before mouseup.

**Comment by gfmoore** [comment]
One point, though right click will clear the drawing area, you can just start drawing again (mouse down) and it (should) clear the display area also.

So I've checked now that when mouse leaves the drawing area it triggers the mouseup event which should stop the drawing. This was quite tricky as it is possible to leave the drawing area so fast that the code doesn't realise. I did a hack which seems to work and also stops the accidental selection of other elements on the page.

It would have been nicer to reposition the mouse, but this is not allowed in a browser as someone could make to click say a cancel button and be made to instead click the Pay me a million pounds button!  

I've now also decided that it is best to simply redraw the pixels, rather than the convert to real world coordinates (which is needed) to do calcs. This stops the slight movement of the curve, but now I have to go and re-fiddle the fill population tweaks.

**Comment by gdcumming** [comment]
0.3.42
Lots of progress here. Fill looks fine. Nice and fast. Curve completes, and goes blue, if (1) mouseup or (2) leave drawing area, top bottom or right edge. Leave that area via left edge and usually completes ok, tho' once I think it didn't. I couldn't reproduce that behaviour, so maybe ok.

One bug: Draw a curve, then draw another one, but see the values for mu and sigma, and the positioning in the display of the mean and SD lines that correspond to the first curve. Switch to normal, then back to custom and see the curve preserved and still with outdated values and line positioning. Clear, then draw a new curve, but values and line positioning still those of the cleared curve.

**Comment by gfmoore** [comment]
One bug: Draw a curve, then draw another one, but see the values for mu and sigma, and the positioning in the display of the mean and SD lines that correspond to the first curve. Switch to normal, then back to custom and see the curve preserved and still with outdated values and line positioning. Clear, then draw a new curve, but values and line positioning still those of the cleared curve.

>> I can't duplicate this? Here is a video clip of mine in action.  (btw I use Active Presenter free version - brilliant.)


[bug #14.zip](https://github.com/gfmoore/ESCI-JS/files/4901918/bug.14.zip)

**Comment by gdcumming** [comment]
0.3.44

Thanks. I hadn't heard of Active Presenter, but it looks neat. (I used Camtasia to make videos for the first ed, because La Trobe has a licence...)

I neglected to mention that I had fill turned on. I obviously hadn't tried with fill off, sorry. Now I find no bug with fill off, but bug with fill on. Hopefully that helps with diagnosis.

Playing around, I did find what may be a related bug:
Fresh download, see normal (50, 20).
Switch to rectangular, use sliders to select mu=60, sigma=15, say. Curve changes, all fine.
Switch back to normal, see normal (50, 20). Fine.
Switch to rectangular, see rectangular curve for (50, 20) but sliders and reported values next to sliders are (60, 15).

--happens whether fill on or off, SD lines on or off
--happens if switch to skew or custom, then back to rectangular

**Comment by gfmoore** [comment]
Yes, Camtasia is a great product, but expensive. I use Jing for screen capture, but they have retired that because the video part uses flash swf. The new version is getting lots of negative reviews. Microsoft now has a new screen capture ability as well, but not as flexible as Jing.

Anyhow, I see what you mean now. I can't imagine how turning on fill causes the problem (so never tested it) I shall investigate.

Programmers only test what they have written, never what they haven't written - that's why we have QA. It's part of a mindset I guess. I wonder if any research has been done into it?

**Comment by gfmoore** [comment]
Fixed. Bug introduced when drawing over bubbles, hadn't recalculated mean and sigma for skew and custom.

**Comment by gdcumming** [comment]
0.3.48

Fill is beautiful, even for very skewed curves. Rectangular is a bit slow, but not a problem.

But a new glitch, for custom--fill goes crazy! Fill is in a vertical stripe pattern

**Comment by gfmoore** [comment]
Fixed. Hope we can close. We can open new issue for anything new, unless there's still a bug here?

**Comment by gdcumming** [comment]
0.3.55 such a high version number!

Sorry, but try a triangular shape in custom, get incomplete steps of fill.

Overall, fill is good, but not quite as good as previous--fill often doesn't quite fill all the space under the curve, tho' close enough to be satisfactory and acceptable. I some smaller tweak of the previous algorithm a promising possibility? That really only had a problem with custom--we can ignore the tiny overspill for skew of 0.1.

**Comment by gdcumming** [comment]
0.3.60

Very happy to accept fill as is now. Slight glitches with some custom: Maybe tweak sometime in the future, but not important.
