### ISSUE TITLE
Display of population, etc

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#19]
Hopefully small and quick.

Panel 2. Click all on, click pop off and all disappear, and all checkboxes cleared. Good. But now click SD or fill on, and we see just those, not the curve. I suggest these should never be visible unless the curve is visible.

Related: It looks like display in the upper panel has data fill in front of SD lines in front of pop curve. Could we reverse that order? Fill now fits much better within the curves, including into the tails--great, I bet that didn't happen automatically! (I've been there.) But curve in front should look neat, and give just a tiny bit more leeway with the fill circles.

**Comment by gdcumming** [comment]
P.S. You made a comment (#11?) about adjustment of the height of the normal curve, with change in sigma. As you no doubt know, the area under any pdf curve is 1.0. So height and width should trade. In ESCI I scale all pop curves so that their max height is (close to) the same, about .8 to .9 of the upper panel display area. Therefore, as sigma for a normal is changed, width changes but height doesn't. If the vertical axis had tick marks and values on it, they would need to change. I confess I'm liking your displays of normal curves, so maybe we leave them as is. 

But, for rectangular, you keep the height constant (as in ESCI). Maybe change that to constant area under the curve, so width and height trade, as for your normal curves?

For custom, maybe we leave the curve shape as drawn, without any vertical scaling to fit the area, or achieve a particular area under the curve. I think that's what you do at present.

I haven't played yet with skew. I think you keep max height at least roughly constant. Maybe that's fine.

**Comment by gfmoore** [comment]
I'll have another look at rectangle height - what you say makes sense - should be a problem - famous last words.

In terms of scalings, I'm afraid these might not be mathematical. There is a balance between being correct mathematically and having to fit in the required space. There is a need to create a visual effect and the values are recorded, hopefully they are correct, but there is so much going on with tweaks and discretising. So for instance the skew is dependent on the (invisible fill of bubbles) that allows me to get a random value. For the custom that is all I can do. The making the skew scale approximately nicely took me ages. There's an if statement for every skew value.
I suspect that a proper and complete analytically correct ESCI and display of such is beyond my abilities - Mathematica might do it :)

**Comment by gdcumming** [comment]
0.3.30

Again, satisficing! I suggest leave heights as they are, with the possible exception of considering changes to rectangle, so area is roughly constant.

There is still the (hopefully small) issue I mentioned first:

Panel 2. Click all on, click pop off and all disappear, and all checkboxes cleared. Good. But now click SD or fill on, and we see just those, not the curve. I suggest these should never be visible unless the curve is visible.

**Comment by gfmoore** [comment]
Height of rectangle now adjusts in relation to sigma. I have had to limit height for small sigma otherwise it overflows the pdf display panel. Is that an issue?

Checkboxes as requested.

Close?

**Comment by gdcumming** [comment]
Generally good, with reasonable changes of height and width, even if not all exactly arithmetically correct in terms of area under curve = 1. However, I think in too many cases the pop max height looks too low. E.g. default normal distribution (sigma = 20) is only about .4 the height of the upper display area. Could we make this around .6 or .7? Yes, we would need to limit curve height when that suggested arrangement would lead to height above the area, but that's fine.

**Comment by gfmoore** [comment]
This has now been changed so that the normal of mu=50 and sd=20 takes up about 0.7 of the height. If the sd > 20 then scales as would expect. If the sd < 20 then I apply a linear scale factor to keep the peak at sd=5 from being too high (now takes up 100% -20 pixels of the height (allowing for the scale). This also has to scale if the height of the browser is reduced or increased. 

There was of course a knock on effect that in order to make the skew look similar I had to go through all the tweaks again. I felt that an sd of 20 didn't look right, so I re-tweaked to make the sd be about 15. (This is for demonstration purposes isn't it. No-one is going to be doing calculations from the log normal as that was used to give the shape!)

Another knock on is that the fill now looks wrong (not sure why), but anyway I am going to re-visit that next anyway.

I hope that this will "satisfice"! :)

I think with all the tweaks and scalings involved in this that I'm almost at a point where I think if we want to go further and be more mathematical I would have to completely overhaul how this is done. I'm not sure it can be done and still give a pleasing effect? Even the normal curve has to great a range of heights for sd from say 30 down to 5.

**Comment by gdcumming** [comment]
0.3.42 (the answer to everything!)

Great! Normal is really nice.

Rectangular: Most changes nice. For sigma = 11 down to 5, no change in height, tho' there is room to progressively raise height a bit more for these very low sigma values.

There's some updating issue. Change sigma or mu and the mean and SD lines don't update correctly. Can switch to normal and back, and see outdated mean and SD lines.

Skew: Nice. If try to change mu and sigma sliders, get only tiny changes to values, and apparently no change to curve. If these sliders are more-or-less disabled for skew, grey them out?

**Comment by gfmoore** [comment]
Rectangular: Most changes nice. For sigma = 11 down to 5, no change in height, tho' there is room to progressively raise height a bit more for these very low sigma values.

>>  Yes, so I've changed the limit value. Best I think I can do otherwise the rect at sigma=20 (the default) is too low.

There's some updating issue. Change sigma or mu and the mean and SD lines don't update correctly. Can switch to normal and back, and see outdated mean and SD lines.

>> It's weird that you are seeing this, as with custom. On mine it looks very reactive? Is there any way you can grab a short video capture of this, or a screen grab so I can see what settings you've checked?

Skew: Nice. If try to change mu and sigma sliders, get only tiny changes to values, and apparently no change to curve. If these sliders are more-or-less disabled for skew, grey them out?

>> Good idea. Done - now if only all features were that simple. :)
>> The tiny changes are due to the Monte Carlo getting of parameters.

**Comment by gfmoore** [comment]
By the way, to what precision do you want the mean and sigma displayed to? The sliders only go up in steps of 1, but the Monte Carlo simulation is allowing two dp?

**Comment by gdcumming** [comment]
0.3.44

Heights and changes are all very good, I think.

Updating issue: I think this is now more clearly described in the new #24. Let me know if it would still help to have a video.

Mu and sigma displayed, and controllable by sliders, as integers is fine for normal and rectangular. For skew and custom, reporting values to 2 dp is probably best. For skew, mu line and SD lines all shift a little as fill clicked off then on. That's fine. Few folks will notice, but if we ever need to explain what's going on, having the more accurate mu and sigma values displayed will probably help.

Closing...

**Comment by gfmoore** [comment]
I knew what the issue was and decided it was better to solve this once and for all. It also would help reduce the spaghetti and lead the way to trying to resolve the fill. So I did some major refactoring. The code is now much cleaner and I can determine if I have a new skew or custom curve and so whether I need to recalculate the mu and sigma. 
I have also split the population fill into two parts one for creating the bubbles array and one for displaying it. This also means I have finer control.

I can now focus on the exact issue of whether to display a bubble or not. To do this I look at the bubble and decide if the curve passes through it, but how? Whatever I can see this being a bit of another slow down to the fill, but it has to be done because there are no real tweaks that work and I just don't like parts of bubbles poking out even under the curve.

It is likely, though I have tested many different combinations that I have re-introduced more bugs. It's like whack-a-mole.

So am re-opening and will now work on the fill algorithm again.

**Comment by gfmoore** [comment]
Okay, so a new algorithm. This goes through each bubble and compares the centre with each pdf co-ordinate within the sample mean width (4 pixels). Use Pythagoras' th to see if the distance between these points is less than the radius. If it is don't display. Works pretty good for normal and skew. Rectangular needed changing from just recording 6 points for the distribution to recording many points to describe the curve. Still found verticals needed an adjustment. The custom also needed a tweak for the vertical sides. Just can't win.

Anyway have a look and let me know. I think it's better than before, though there are occasional ones that peek? through,

**Comment by gdcumming** [comment]
0.3.48

OK I've played some more with fill. In nearly every case I'll stick with my earlier remark that it's beautiful. Even for all values of skew, except that for +/- 0.1 skew there are a few circles that peek partly outside the curve. Ditto for parts of most custom curves--tho' these have the bigger fill problem.

We could easily live with the small-skew peeking, unless it's a simple tweak to fix. Not worth big effort. Satisfice! Hopefully, the bug fix for custom fill will fix any peeking there.

**Comment by gdcumming** [comment]
0.3.55

Superseded by #14, so shall close
