### ISSUE TITLE
Sampling distribution curve shape

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#25]
0.3.48

A very narrow tall sdc has little dips below the axis on each side.

E.g. sigma=5, N=100. As it grows, two little 'S' or 'J' shaped glitches to the smooth normal shape emerge, one at each tail.

**Comment by gfmoore** [comment]
This was due to a d3 curve interpolation, which was used to smooth out pointiness of peak.
So now use a 100x more points for the curve - impact to slow things down more and use more memory.

Does the height need re adjusting.

Perhaps you might care again to explain how I might calculate height using area underneath. Area can only be in terms of frequencies of the 4 pixel sample bubbles? Unless I redo heap algorithm as we have been discussing (though I still haven't really had time to digest and think about what you have said previously.)  I'm a bit dense here. ;)

:)

**Comment by gdcumming** [comment]
0.3.55

Again, apologies that turned out to be tricky. I assumed that you'd used some formula for the normal distribution, which is so easy in Excel. I can see that having SDC on does slow down sampling a tiny bit, tho' not enough to worry about.

The curves now look to me fine, with no trace of end glitches. I've tried narrow and wide for various situations, and the height seems to me very good. To my eye, the area of means above the curve is, on average, very similar to the blank area under the curve.

Closing...

**Comment by gfmoore** [comment]
So do you count the number of sample means above the curve and below?

Yes there is the formula in jStat (many many formulae), but I didn't use enough points and d3 provides some "interpolations" to smooth the curve between data points

**Comment by gdcumming** [comment]
Ah, I see.

To judge how well the curve fits the heap, I eyeball toppling means that poke above the curve over onto other columns that don't reach up to the curve. Very roughly. 

As I said, I think it's great. (So I didn't follow up on your earlier request to explain again about area under the curve, and little squares.) Let's call this done--and be very happy with it!
