### ISSUE TITLE
Better Figures in Chapters 4, 5

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#27]
0.9.0 Beta

I'm working on Chapters 4 and 5, where **dances** is the key resource. Making screen shots for the Figures prompts these requests:

--Insert the two labels in the upper display area, as in ESCI CIjumping. 'Probability density' on vertical axis at left in upper display area. Also 'Population' in upper left corner of that area. I'm hoping it's not very difficult to move the zero end of the two horizontal axes (at very top and very bottom) in a bit, so there is space on the outside of the vertical axis for the first requested label. If I'm wrong, we should consult. (There's no need to have little tick marks on that vertical axis.)

--Make the numbers on very top and very bottom horizontal axes more visible. Maybe just a little larger, but more importantly bold? Or a thicker font?

--No tips to the two right hand display areas

**Comment by gfmoore** [comment]
Okay, so I've made the axis numbers larger and bold, I've added population, but sorry, I'm not going to add the 'probability density'. The reason is that this will probably break all the tweaks and fiddles I've done in the last two months to get this far. I could try and add it on the inside?

If I was a better programmer I would have thought about such shifts and indeed the standard for d3 is to create margins, which I did, but there are so many tweak to the pixel positions and to adjust "real" coords that it would open up a can of worms and I'm not going to invest the time in tracking down and re-fixing things. So very sorry, but we are going to have to live with it.

On distributions I'm trying to be more flexible (a lesson learnt), but even there it is proving problematic. Sometimes vertical lines just don't hit the proper tick mark, so I adjust by a pixel and that fixes it, sort of. Back to the old story of reactive and responsive sizes. The old days of absolute positioning are gone.

**Comment by gdcumming** [comment]
0.9.4 Beta

Bigger bolder numbers look great, as do the larger mu and mu0 at the bottom, when their lines are visible.

I guessed that it would be a nightmare even to think about shifting the 0 end of the axis in a bit. Yes, don't touch that.

Could you try putting 'Probability density' just inside that left hand vertical? (Maybe move 'Population' over a bit)

Thanks...

**Comment by gfmoore** [comment]
Added.
