### ISSUE TITLE
To Clear or not to Clear?

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/ESCI-JS#8]
The big buffer means that we don’t need an automatic Clear when those changes referred to in the previous issue (Capture of mu) are made by the user. Better than ESCI. Good.

We do have an automatic Clear if N is changed. Good.

Still need to have an automatic Clear before restart of sampling after a change in selection of CIs displayed or not. At present it’s easy to get % capturing values of greater than 100%.

Maybe show numbers and % for capture only when CIs are displayed, and have been displayed for the current full run, i.e. since the last Clear.

Can also get values above 100% if turn display of mean heap (and curve on that heap?) off, take more samples, maybe turn mean heap on again. I don’t know whether counts of captures are correct in such cases. It may be best to be conservative and do an automatic Clear when any of those are toggled on or off? 

Are there other changes or situations in which an automatic Clear is needed, to clear the buffer and restart the various counts?

**Comment by gfmoore** [comment]
__Quote: Still need to have an automatic Clear before restart of sampling after a change in selection of CIs displayed or not. At present it’s easy to get % capturing values of greater than 100%."__

I'm wondering if I've now fixed this by fixing the display capture stats or not only when CI etc selected. Can you review please.

__quote: "Maybe show numbers and % for capture only when CIs are displayed, and have been displayed for the current full run, i.e. since the last Clear."__

I think I've covered this one now - in issue 7 Capture of mu?

__quote: "Can also get values above 100% if turn display of mean heap (and curve on that heap?) off, take more samples, maybe turn mean heap on again. I don’t know whether counts of captures are correct in such cases. It may be best to be conservative and do an automatic Clear when any of those are toggled on or off?"__

I refer to above.
Again can you recheck, it looks ok to me, but then I'm very close to the fire. btw you make a great quality assurance person :)

__quote: "Are there other changes or situations in which an automatic Clear is needed, to clear the buffer and restart the various counts?"__

hahaha I've got no idea, we need Marvin the Paranoid Android - brain the size of a planet - to keep track of this. 
(Hitchhikers Guide to the Galaxy - Douglas Adams) 

Again can we close this and raise new issues separately if there are any now.

**Comment by gfmoore** [comment]
SE Lines should now clear properly

**Comment by gdcumming** [comment]
I fully sympathise with your comments in #17. I've had several goes at setting out the logic of clear/stop/action for each control. I wrote some stuff for this # yesterday but lost it. I'll close this and have another go in answer to #17. Phew...
